In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
np.shape(arr3)

(3, 3)

In [6]:
import numpy as np
import pandas as pd

df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [7]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [8]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]])

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [9]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [10]:
np.random.randint(0, 4, (3, 3))

array([[0, 0, 2],
       [3, 2, 0],
       [0, 1, 1]])

In [11]:
np.random.randint(0, 5, (3, 3))

array([[4, 2, 4],
       [0, 4, 1],
       [4, 2, 1]])

In [12]:
np.random.randint(0, 5, 3)

array([4, 3, 1])

In [13]:
np.random.randint(0, 6, (3, 3))

array([[0, 2, 0],
       [1, 2, 2],
       [0, 1, 5]])

In [14]:
my_array = np.array([x for x in range(10)])

In [15]:
my_array[5]

5

In [16]:
my_array[-1]

9

In [17]:

my_array[3:6]


array([3, 4, 5])

In [18]:
my_array[1:8:3]

array([1, 4, 7])

In [19]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])

In [20]:
my_array[1][2]

12

In [21]:
my_array[1,2]

12

In [22]:
my_array[1]

array([10, 11, 12, 13])

In [23]:
my_array[:,2]

array([ 3, 12, 47])

In [24]:
my_array[1:, 1:3]

array([[11, 12],
       [46, 47]])

In [25]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [26]:
my_array = np.random.randint(1, 100, (4, 6))

In [27]:
my_array

array([[63, 55, 19, 10, 33, 75],
       [73, 88, 55, 27, 71, 77],
       [54, 12, 39, 23, 50,  4],
       [41,  7, 93, 37, 10, 22]])

In [28]:
my_slice = my_array[1:3, 2:4]

In [29]:
my_slice

array([[55, 27],
       [39, 23]])

In [30]:
my_slice[:] = 0

In [31]:
my_array

array([[63, 55, 19, 10, 33, 75],
       [73, 88,  0,  0, 71, 77],
       [54, 12,  0,  0, 50,  4],
       [41,  7, 93, 37, 10, 22]])

In [32]:
a = np.array([3,6,9])
b = np.array([12,15,18])

In [34]:
result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [35]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [36]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[8, 4, 1, 8, 4],
       [8, 6, 4, 0, 2],
       [6, 4, 8, 5, 9],
       [5, 8, 3, 7, 2]])

In [37]:
my_array

array([8, 4, 1, 8, 4, 8, 6, 4, 0, 2, 6, 4, 8, 5, 9, 5, 8, 3, 7, 2])

In [38]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])


In [39]:
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [40]:
my_array.flatten()


array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [41]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[2, 8, 2, 8],
       [2, 3, 3, 1],
       [2, 9, 9, 1]])

In [42]:
my_array<5

array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False,  True]])

In [43]:
my_array[my_array<5]

array([2, 2, 2, 3, 3, 1, 2, 1])

In [44]:
my_array[my_array<5]

array([2, 2, 2, 3, 3, 1, 2, 1])

In [45]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[2, 2],
       [2, 3],
       [2, 9]])

In [46]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[7, 1, 8, 7, 2, 6],
       [4, 4, 3, 8, 4, 2],
       [9, 6, 2, 5, 0, 9],
       [2, 7, 1, 6, 4, 7]])

In [47]:
np.sort(my_array, axis=1)

array([[1, 2, 6, 7, 7, 8],
       [2, 3, 4, 4, 4, 8],
       [0, 2, 5, 6, 9, 9],
       [1, 2, 4, 6, 7, 7]])

In [48]:
np.sort(my_array, axis=0)

array([[2, 1, 1, 5, 0, 2],
       [4, 4, 2, 6, 2, 6],
       [7, 6, 3, 7, 4, 7],
       [9, 7, 8, 8, 4, 9]])